### ISSUE TITLE
Does lispbox have CFFI and thread support?

### ISSUE THREAD

**Issue by mcandre** [andreer/lispbox#1]
I've had a tough time finding a Common Lisp with CFFI and thread support. "sudo apt-get install sbcl" crashes on Xen. :(

**Comment by andreer** [comment]
I've had the same problem with sbcl on Xen. Lispbox includes Clozure CL, which has FFI and threads. It also includes Quicklisp, which should enable you to install CFFI and Bordeaux-threads as easily as (ql:quickload 'cffi) (ql:quickload 'bordeaux-threads).

Unfortunately, I've had some problems making the Linux build work reliably on all Linux distributions. Hopefully it works for you! If not, please let me know along with some info on your distribution etc.

– Andreas

**Comment by mcandre** [comment]
That's good to hear.
