### ISSUE TITLE
Command line emacs

### ISSUE THREAD

**Issue by mcandre** [andreer/lispbox#2]
Could you add a command line version of Emacs to lispbox? I really prefer using Lisp through a terminal.

**Comment by andreer** [comment]
To run emacs in your terminal, append " -nw" to the last line in lispbox.sh.

lispbox.sh should probably pass any arguments on to emacs, so you could just say "lispbox.sh -nw". I'll put that in the next version.

**Comment by mcandre** [comment]
Yeah, Emacs -nw works for me. I've got a pretty good bash profile and ccl-init. Check them out here: https://github.com/mcandre/dotfiles

**Comment by mcandre** [comment]
If you include rlwrap and run gen-completions.ccl during installation, then CCL gets tab completion without requiring Emacs/SLIME.

https://github.com/mcandre/dotfiles/blob/master/gen-completions.ccl

**Comment by mcandre** [comment]
Shebangs are easier if you include "ccl", a little shell script, in the installation. https://github.com/mcandre/dotfiles/blob/master/ccl

For an example script with a shebang, see http://www.assembla.com/code/mcandre/subversion/nodes/common-lisp/hunchtest.cl?rev=139

**Comment by Gagege** [comment]
Shouldn't this issue be closed?

**Comment by andreer** [comment]
I agree. :-)
