### ISSUE TITLE
Unsure how to build

### ISSUE THREAD

**Issue by mcandre** [andreer/lispbox#3]
I've forked lispbox for experimentation. How do you build Lispbox?

```
$ make -f GNUmakefile.clozurecl 
make: *** No rule to make target `binary-archives/.tar.gz', needed by `staging-archives/.tar.gz'.  Stop.
```

**Comment by gigamonkey** [comment]
Sorry for the delay. Anyway, the GNUmakefile.\* are sub-makefiles invoked by the main one. And the README.source should explain more or less how things work.
